name: session_mate_cli
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  sweetcore:
    path: ../sweetcore
  flutter_driver:
    sdk: flutter
  args: ^2.4.2

  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
