name: session_mate_cli
description: The command line tool for SessionMate
version: 0.5.0
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter_driver:
    sdk: flutter
  
  ansicolor: ^2.0.1
  args: ^2.4.2
  get_it: ^7.6.0
  mockito: ^5.4.1
  path: ^1.8.1
  pub_updater: ^0.3.0
  usage: ^4.1.1
  yaml: ^3.1.2
  
  sweetcore:
    git:
      url: git@github.com:filledstacks/sweetcore.git
  
  session_mate_core: ^0.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependency_overrides:
  sweetcore:
    path: ../sweetcore
  session_mate_core:
    path: ../session_mate_core

executables:
  session_mate: