// Mocks generated by Mockito 5.4.2 from annotations
// in session_mate_cli/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:session_mate_cli/src/services/brew_service.dart' as _i2;
import 'package:session_mate_cli/src/services/process_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BrewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrewService extends _i1.Mock implements _i2.BrewService {
  @override
  _i3.Future<String> getCurrentVersion() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentVersion,
          [],
        ),
        returnValue: _i3.Future<String>.value(''),
        returnValueForMissingStub: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getLatestVersion() => (super.noSuchMethod(
        Invocation.method(
          #getLatestVersion,
          [],
        ),
        returnValue: _i3.Future<String>.value(''),
        returnValueForMissingStub: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> hasLatestVersion() => (super.noSuchMethod(
        Invocation.method(
          #hasLatestVersion,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> install() => (super.noSuchMethod(
        Invocation.method(
          #install,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update() => (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ProcessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessService extends _i1.Mock implements _i4.ProcessService {
  @override
  _i3.Future<void> runPubGlobalActivate() => (super.noSuchMethod(
        Invocation.method(
          #runPubGlobalActivate,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> runPubGlobalList() => (super.noSuchMethod(
        Invocation.method(
          #runPubGlobalList,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> runBrewInfo() => (super.noSuchMethod(
        Invocation.method(
          #runBrewInfo,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> runBrewInstallPackage() => (super.noSuchMethod(
        Invocation.method(
          #runBrewInstallPackage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> runBrewUpgradePackage() => (super.noSuchMethod(
        Invocation.method(
          #runBrewUpgradePackage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void logSuccessStatus(int? exitCode) => super.noSuchMethod(
        Invocation.method(
          #logSuccessStatus,
          [exitCode],
        ),
        returnValueForMissingStub: null,
      );
}
