name: Build CLI executables

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  compile:
    name: Compile SessionMate
    strategy:
      matrix:
        include:
          # - runs-on: ubuntu-latest
          #   binary-name: sessionmate_linux_amd64
          - runs-on: macos-latest
            binary-name: sessionmate_macos_amd64
          - runs-on: macos-latest-large
            binary-name: sessionmate_macos_arm
          # - runs-on: windows-latest
          #   binary-name: sessionmate_windows.exe
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Give GitHub Actions access to sweetcore
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SWEETCORE_REPLOY_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: mkdir ${{ matrix.runs-on }}
      - run: dart compile exe bin/sessionmate.dart -o ${{ matrix.runs-on }}/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.runs-on }}
          path: ${{ matrix.runs-on }}
  
  release:
    needs: compile
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bin-macos-latest
          path: bin-macos
      - uses: actions/download-artifact@v2
        with:
          name: bin-macos-latest-large
          path: bin-macos-large
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin-*/*
