name: Build CLI executables

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    name: Compile SessionMate
    strategy:
      matrix:
        include:
          # - runs-on: ubuntu-latest
          #   binary-name: sessionmate_linux_amd64
          - runs-on: macos-latest
            compressed-name: sessionmate_macos_x86_64.tar.gz
          - runs-on: macos-latest-large
            compressed-name: sessionmate_macos_arm64.tar.gz
          # - runs-on: windows-latest
          #   binary-name: sessionmate_windows.exe
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Give GitHub Actions access to sweetcore
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SWEETCORE_REPLOY_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: mkdir ${{ matrix.runs-on }}
      - run: dart compile exe bin/sessionmate.dart -o ${{ matrix.runs-on }}/sessionmate
      - run: tar -cvzf ${{ matrix.runs-on }}/${{ matrix.compressed-name }} ${{ matrix.runs-on }}/sessionmate
      - uses: actions/upload-artifact@v2
        with:
          name: compressed-${{ matrix.runs-on }}
          path: ${{ matrix.runs-on }}
  
  release:
    needs: compile
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: compressed-macos-latest
          path: compressed-macos
      - uses: actions/download-artifact@v2
        with:
          name: compressed-macos-latest-large
          path: compressed-macos-large
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            compressed-*/*.tar.gz
      # - name: Bump homebrew-tap formula
      #   uses: mislav/bump-homebrew-formula-action@v2
      #   env:
      #     COMMITTER_TOKEN: ${{ secrets.BREW_TOKEN }}
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     formula-name: sessionmate
      #     formula-path: sessionmate.rb
      #     homebrew-tap: FilledStacks/homebrew-tap
